---
- name: "Instalando Docker e Docker Compose 2"
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: repository docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Install Docker CE
      apt:
        name: ['docker-ce']
        update_cache: yes
    - name: Run and enable docker
      service:
        name: docker
        state: started
        enabled: true
    - name: Install docker-compose from official github repo
      get_url: 
        url : https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'