---
- name: "Instalando Docker e Docker Compose"
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest